package com.codeproj.traininghandler.model;

// Generated 07-Jan-2014 17:36:37 by Hibernate Tools 4.0.0

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private long userRoleId;
	private User user;
	private String authority;

	public Authorities() {
	}

	public Authorities(long userRoleId, User user, String authority) {
		this.userRoleId = userRoleId;
		this.user = user;
		this.authority = authority;
	}

	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
